[package]
name = "deeprox"
version = "0.1.0"
authors = ["Ben Lichtman"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0.18"
openssl = "0.10"
webpki-roots = "0.19.0"
rustls = "0.17"
rand = "0.7"
tokio-rustls = "0.13"
# native-tls = "0.2"
# tokio-tls = "0.3"
# tokio = { version = "0.2", features = ["full"] }
# regex = "1.3.7"
httparse = "1.3.4"
url = "2.1.1"
async-std = { version = "1.6.0", features = ["attributes"] }
async-tls = "0.7.0"
futures = "0.3.5"
async-h1 = { path = "/home/ben/repos/other_repos/async-h1" }
http-types = "2.0.1"
piper = "0.1.2"
